# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if 'topology' in bld.env['CCN_plugins']:
        obj = bld.create_ns3_program('rocketfuel-maps-cch-to-annotaded', ['ccnSIM'])
        obj.source = 'rocketfuel-maps-cch-to-annotaded.cc'
