## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
#
# Copyright (c) 2011-2013, Regents of the University of California
#                          Alexander Afanasyev
#
# GNU 3.0 license, See the LICENSE file for more information
#
# Author: Alexander Afanasyev <alexander.afanasyev@ucla.edu>
#

import os
from waflib import Logs, Utils, Options, TaskGen, Task
from waflib.Errors import WafError

import wutils

def options(opt):
    opt = opt.add_option_group ('ccnSIM Options')
    opt.add_option('--enable-ccn-plugins',
                   help="""Enable CCN plugins (may require patching).  topology plugin enabled by default""",
                   dest='enable_ccn_plugins')

    opt.add_option('--disable-ccn-plugins',
                   help="""Enable CCN plugins (may require patching).  topology plugin enabled by default""",
                   dest='disable_ccn_plugins')

    opt.add_option('--pyccn-install-path', dest='pyccn_install_path',
                   help="""Installation path for PyCCN (by default: into standard location under PyCCN folder""")

REQUIRED_BOOST_LIBS = ['graph']

def required_boost_libs(conf):
    conf.env.REQUIRED_BOOST_LIBS += REQUIRED_BOOST_LIBS

def configure(conf):
    conf.env['ENABLE_CCNSIM']=False;

    if not conf.env['LIB_BOOST']:
        conf.report_optional_feature("ccnSIM", "ccnSIM", False,
                                     "Required boost libraries not found")
        Logs.error ("ccnSIM will not be build as it requires boost libraries of version at least 1.48")
        conf.env['MODULES_NOT_BUILT'].append('ccnSIM')
        return
    else:
        present_boost_libs = []
        for boost_lib_name in conf.env['LIB_BOOST']:
            if boost_lib_name.startswith("boost_"):
                boost_lib_name = boost_lib_name[6:]
            if boost_lib_name.endswith("-mt"):
                boost_lib_name = boost_lib_name[:-3]
            present_boost_libs.append(boost_lib_name)

        missing_boost_libs = [lib for lib in REQUIRED_BOOST_LIBS if lib not in present_boost_libs]

        if missing_boost_libs != []:
            conf.report_optional_feature("ccnSIM", "ccnSIM", False,
                                         "ccnSIM requires boost libraries: %s" % ' '.join(missing_boost_libs))
            conf.env['MODULES_NOT_BUILT'].append('ccnSIM')

            Logs.error ("ccnSIM will not be build as it requires boost libraries: %s" % ' '.join(missing_boost_libs))
            Logs.error ("Please upgrade your distribution or install custom boost libraries (http://ccnsim.net/faq.html#boost-libraries)")
            return

        boost_version = conf.env.BOOST_VERSION.split('_')
        if int(boost_version[0]) < 1 or int(boost_version[1]) < 48:
            conf.report_optional_feature("ccnSIM", "ccnSIM", False,
                                         "ccnSIM requires at least boost version 1.48")
            conf.env['MODULES_NOT_BUILT'].append('ccnSIM')

            Logs.error ("ccnSIM will not be build as it requires boost libraries of version at least 1.48")
            Logs.error ("Please upgrade your distribution or install custom boost libraries (http://ccnsim.net/faq.html#boost-libraries)")
            return

    conf.env['CCN_plugins'] = ['topology', 'ip-faces']
    if Options.options.enable_ccn_plugins:
        conf.env['CCN_plugins'] = conf.env['CCN_plugins'] + Options.options.enable_ccn_plugins.split(',')

    if Options.options.disable_ccn_plugins:
        conf.env['CCN_plugins'] = conf.env['CCN_plugins'] - Options.options.disable_ccn_plugins.split(',')

    if Options.options.pyccn_install_path:
        conf.env['PyCCN_install_path'] = Options.options.pyccn_install_path

    conf.env['ENABLE_CCNSIM']=True;
    conf.env['MODULES_BUILT'].append('ccnSIM')

    conf.report_optional_feature("ccnSIM", "ccnSIM", True, "")

def build(bld):
    deps = ['core', 'network', 'point-to-point']
    deps.append ('internet') # Until RttEstimator is moved to network module
    if 'ns3-visualizer' in bld.env['NS3_ENABLED_MODULES']:
        deps.append ('visualizer')

    if 'topology' in bld.env['CCN_plugins']:
        deps.append ('topology-read')
        deps.append ('mobility')

    if 'mobility' in bld.env['CCN_plugins']:
        deps.append ('mobility')

    module = bld.create_ns3_module ('ccnSIM', deps)
    module.module = 'ccnSIM'
    module.features += ' ns3fullmoduleheaders'
    module.uselib = 'BOOST BOOST_IOSTREAMS'

    headers = bld (features='ns3header')
    headers.module = 'ccnSIM'

    if not bld.env['ENABLE_CCNSIM']:
        bld.env['MODULES_NOT_BUILT'].append('ccnSIM')
        return

    module.source = bld.path.ant_glob(['model/**/*.cc',
                                       'model/cs/utility-caching/*.cc',
                                       'apps/*.cc',
                                       'utils/**/*.cc',
                                       'helper/**/*.cc',
                                       'ccn.cxx/**/*.cc',
                                       ])
    module.full_headers = [p.path_from(bld.path) for p in bld.path.ant_glob([
                           'utils/**/*.h',
                           'model/**/*.h',
                           'model/cs/utility-caching/*.h',
                           'apps/**/*.h',
                           'helper/**/*.h',
                           'ccn.cxx/**/*.h',
                           ])]

    headers.source = [
        "helper/ccn-stack-helper.h",
        "helper/ccn-app-helper.h",
        "helper/ccn-header-helper.h",
        "helper/ccn-face-container.h",
        "helper/ccn-global-routing-helper.h",
        "helper/ccn-link-control-helper.h",

        "apps/ccn-app.h",

        "model/ccn-common.h",
        "model/ccn-l3-protocol.h",
        "model/ccn-face.h",
        "model/ccn-app-face.h",
        "model/ccn-net-device-face.h",
        "model/ccn-common-object.h",
        "model/ccn-interest.h",
        "model/ccn-interestresponse.h",
        "model/ccn-data.h",
        "model/ccn-name-components.h",
        "model/ccn-name.h",

        "ccn.cxx/blob.h",
        "ccn.cxx/name-component.h",
        "ccn.cxx/name.h",
        "ccn.cxx/exclude.h",
        "ccn.cxx/ccn-api-face.h",

        "model/cs/utility-caching/UtilityFunctions.h",
        "model/cs/utility-caching/UtilityCachingHelper.h",
        "model/cs/ccn-content-store.h",
        "model/sm/ccn-security-module.h",
        "model/cs/ccn-content-storage.h",

        "model/fib/ccn-fib.h",
        "model/fib/ccn-fib-entry.h",

        "model/pit/ccn-pit.h",
        "model/pit/ccn-pit-entry.h",
        "model/pit/ccn-pit-entry-incoming-face.h",
        "model/pit/ccn-pit-entry-outgoing-face.h",

        "model/fw/ccn-forwarding-strategy.h",
        "model/fw/ccn-fw-tag.h",

"model/wire/icnx/tlv_base.h",
"model/wire/icnx/tlv_endiandata.h",
"model/wire/icnx/tlv_rawdata.h",
"model/wire/icnx/tlv_container.h",
"model/wire/icnx/tlv_factory.h",
"model/wire/icnx/ccn-1.0_tlv-id.h",
"model/wire/icnx/RangeDataTemplate.h",
"model/wire/icnx/ccn-1.0_interest_tlv.h",
"model/wire/icnx/ccn-1.0_interestresponse_tlv.h",
"model/wire/icnx/ccn-1.0_interestresp_returncode_tlv.h",
"model/wire/icnx/ccn-1.0_content_tlv.h",
"model/wire/icnx/ccn-1.0_expiry_tlv.h",
"model/wire/icnx/ccn-1.0_cachetime_tlv.h",
"model/wire/icnx/ccn-1.0_intlife_tlv.h",
"model/wire/icnx/ccn-1.0_name_tlv.h",
"model/wire/icnx/ccn-1.0_payload_tlv.h",
"model/wire/icnx/ccn-1.0_interest_hop_tlv.h",
"model/wire/icnx/ccn-1.0_app_tlv.h",
"model/wire/icnx/ccn-1.0_mesg_tlv.h",
"model/wire/icnx/ccn-1.0_payldtype_tlv.h",
"model/wire/icnx/ccn-1.0_ipidm_tlv.h",
  "model/wire/icnx/ccn-1.0_namesegment_tlv.h",
  "model/wire/icnx/ccn-1.0_pad_tlv.h",
  "model/wire/icnx/ccn-1.0_keyidrestr_tlv.h",
  "model/wire/icnx/ccn-1.0_ipid_tlv.h",
  "model/wire/icnx/ccn-1.0_flow_tlv.h",
  "model/wire/icnx/ccn-1.0_objhashrestr_tlv.h",
  "model/wire/icnx/ccn-1.0_cert_tlv.h",
  "model/wire/icnx/ccn-1.0_crc32_tlv.h",
  "model/wire/icnx/ccn-1.0_crc32c_tlv.h",
  "model/wire/icnx/ccn-1.0_ec_secp256k1_tlv.h",
  "model/wire/icnx/ccn-1.0_ec_secp384r1_tlv.h",
  "model/wire/icnx/ccn-1.0_hmac_sha256_tlv.h",
  "model/wire/icnx/ccn-1.0_keyname_tlv.h",
  "model/wire/icnx/ccn-1.0_keyid_tlv.h",
  "model/wire/icnx/ccn-1.0_link_tlv.h",
  "model/wire/icnx/ccn-1.0_publickey_tlv.h",
  "model/wire/icnx/ccn-1.0_publickeylocation_tlv.h",
  "model/wire/icnx/ccn-1.0_rfc793_tlv.h",
  "model/wire/icnx/ccn-1.0_rsa_sha256_tlv.h",
  "model/wire/icnx/ccn-1.0_sigtime_tlv.h",
  "model/wire/icnx/ccn-1.0_validationalg_tlv.h",
  "model/wire/icnx/ccn-1.0_validationalgpayld_tlv.h",
  "model/wire/icnx/ccn-1.0_vmac128_tlv.h",



  "model/wire/ccn-wire.h",

        "utils/ccn-limits.h",
        "utils/ccn-rtt-estimator.h",

        "model/wire/icnx/pugixml.h",
	"model/wire/icnx/pugiconfig.h",

        # "utils/tracers/ipv4-app-tracer.h",
        # "utils/tracers/ipv4-l3-tracer.h",
        # "utils/tracers/ipv4-rate-l3-tracer.h",
        # "utils/tracers/ipv4-seqs-app-tracer.h",

        "utils/tracers/l2-rate-tracer.h",
        "utils/tracers/l2-tracer.h",
        "utils/tracers/ccn-app-delay-tracer.h",
        "utils/tracers/ccn-cs-tracer.h",
        "utils/tracers/ccn-l3-aggregate-tracer.h",
        "utils/tracers/ccn-l3-tracer.h",
        "utils/tracers/ccn-l3-rate-tracer.h",

        "apps/callback-based-app.h",
        ]

    if 'topology' in bld.env['CCN_plugins']:
        headers.source.extend ([
            "plugins/topology/rocketfuel-weights-reader.h",
            "plugins/topology/annotated-topology-reader.h",
            ])
        module.source.extend (bld.path.ant_glob(['plugins/topology/*.cc']))
        module.full_headers.extend ([p.path_from(bld.path) for p in bld.path.ant_glob(['plugins/topology/**/*.h'])])

    if 'mobility' in bld.env['CCN_plugins']:
        headers.source.extend ([
            "plugins/mobility/spring-mobility-model.h",
            "plugins/mobility/spring-mobility-helper.h",
            ])
        module.source.extend (bld.path.ant_glob(['plugins/mobility/*.cc']))
        module.full_headers.extend ([p.path_from(bld.path) for p in bld.path.ant_glob(['plugins/mobility/**/*.h'])])

    if 'ip-faces' in bld.env['CCN_plugins']:
        headers.source.extend ([
            "plugins/ip-faces/ccn-ip-faces-helper.h",
            ])
        module.source.extend (bld.path.ant_glob(['plugins/ip-faces/*.cc']))
        module.full_headers.extend ([p.path_from(bld.path) for p in bld.path.ant_glob(['plugins/ip-faces/**/*.h'])])

    # bld.install_files('${INCLUDEDIR}/%s%s/ns3/ccnSIM' % (wutils.APPNAME, wutils.VERSION), ccnSIM_headers, relative_trick=True)
    # bld.install_files('$PREFIX/include', ccnSIM_headers)

    tests = bld.create_ns3_module_test_library('ccnSIM')
    tests.source = bld.path.ant_glob('test/*.cc')

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse ('examples')

    bld.recurse ('tools')

    bld.ns3_python_bindings()

    if bld.env['ENABLE_PYTHON_BINDINGS']:
        if bld.env['PyCCN_install_path']:
            bld (features = "py",
                 source = bld.path.ant_glob (["PyCCN/**/*.py"]),
                 install_from = "PyCCN",
                 install_path = bld.env['PyCCN_install_path'])

@TaskGen.feature('ns3fullmoduleheaders')
@TaskGen.after_method('process_rule')
def apply_ns3fullmoduleheaders(self):
    # ## get all of the ns3 headers
    ns3_dir_node = self.bld.path.find_or_declare("ns3")

    mode = getattr(self, "mode", "install")

    for filename in set(self.to_list(self.full_headers)):
        src_node = self.path.find_resource(filename)
        if src_node is None:
            raise WafError("source ns3 header file %s not found" % (filename,))
        dst_node = ns3_dir_node.find_or_declare(src_node.path_from(self.bld.path.find_dir('src')))
        assert dst_node is not None

        relpath = src_node.parent.path_from(self.bld.path.find_dir('src'))

        task = self.create_task('ns3header')
        task.mode = getattr(self, 'mode', 'install')
        if task.mode == 'install':
            self.bld.install_files('${INCLUDEDIR}/%s%s/ns3/%s' % (wutils.APPNAME, wutils.VERSION, relpath),
                                   [src_node])
            task.set_inputs([src_node])
            task.set_outputs([dst_node])
        else:
            task.header_to_remove = dst_node
